#!/usr/bin/env python3

import functools
import time

import cv2
import numpy as np
import pinocchio as pin
import pyrealsense2 as rs
import rtde_receive
import rtde_control
import math
import signal
import sys
from pathlib import Path


from concurrent.futures import ThreadPoolExecutor

# Allow this file to be launched directly from any working directory. The
# inference directory contains robotiq_socket.py, while CBF_DIR contains
# legacy top-level modules imported by the CBF code (Controller, scripts, etc.).
CBF_DIR = Path(__file__).resolve().parents[1]
INFERENCE_DIR = CBF_DIR.parent
for module_dir in (INFERENCE_DIR, CBF_DIR):
    if str(module_dir) not in sys.path:
        sys.path.insert(0, str(module_dir))

from robotiq_socket import RobotiqCModelURCap
from openpi_client import image_tools, websocket_client_policy

from cbf_python.scripts.example_cbf_optimal import load_config, setup_controller
from sharework import loadSharework
from cbf_python.Command_bridge.joint_command_bridge import JointStateCommandBridge
from cbf_python.Controller.optimal_cbf_task_controller import BCFOptimalController, ControllerConfig

def _handle_robot_sigint(rtde_c, bridge, signum, frame):
    """Stop active servo motion immediately, then enter normal cleanup."""
    print("\nCtrl+C received: stopping robot immediately...", flush=True)
    if rtde_c is not None:
        try:
            rtde_c.servoStop()
        except Exception:
            try:
                rtde_c.stopJ(2.0)
            except Exception:
                pass
    if bridge is not None:
        try:
            bridge.shutdown()
        except Exception:
            pass
    raise KeyboardInterrupt

# ============================================================
# CONFIG
# ============================================================

ROBOT_IP = "192.168.10.2"

FRONT_SERIAL = "116622071830"
WRIST_SERIAL = "922612070587"

SERVER_HOST = "localhost"
SERVER_PORT = 8000

CAM_W = 640
CAM_H = 480
CAM_FPS = 30
IMG_SIZE = 224

PROMPT = "Pick up the black metal object and place it in the black box"
SAFETY_PROMPT = "Stay away from the human"

# ============================================================
# EXECUTION
# ============================================================

# High frequency UR servo / B-CBF loop (500 Hz = 0.002 s)
SERVO_HZ = 500
SERVO_DT = 1.0 / SERVO_HZ

# Policy action execution (20 Hz = 0.05 s)
ACTION_HZ = 20
ACTION_DT = 1.0 / ACTION_HZ

# Give the first target a slower transition from the measured robot state.
FIRST_TARGET_TIME = 0.50

# 500 / 20 = 25 servo commands per policy action
SERVO_STEPS_PER_ACTION = SERVO_HZ // ACTION_HZ

# π0.5 currently outputs 30 actions
ACTION_HORIZON = 30

# Use the complete prediction unless early replanning is needed
EXECUTE_ACTIONS = 30

# Nominal duration: 0.50 s to the first target, then 0.05 s per target.
CHUNK_DURATION = FIRST_TARGET_TIME + (EXECUTE_ACTIONS - 1) * ACTION_DT

LOOKAHEAD_TIME = 0.10
GAIN = 100


# ============================================================
# NON-FATAL POLICY LIMITS
#
# These limits CLAMP the trajectory.
# They do not terminate execution.
# ============================================================

MAX_FIRST_DELTA = 0.25

MAX_STEP_DELTA = 0.05

MAX_CHUNK_DELTA = 0.45


# ============================================================
# EARLY REPLAN
#
# This also does NOT terminate the program.
#
# If the robot falls behind by more than this:
#
#     abandon remaining a    from robotiq_socket import RobotiqCModelURCap

#     -> observe
#     -> infer again
# ============================================================

REPLAN_TRACKING_ERROR = 0.15


# ============================================================
# OPTIONAL CRATE SAFETY SUPERVISOR
#
# The four opening points must be measured in the robot-base frame and ordered
# around the opening: P1 -> P2 -> P3 -> P4. The normal generated by
# (P2 - P1) x (P4 - P1) must point out of the crate. Leave the feature
# disabled until the calibrated points below have been entered.
# ============================================================

CRATE_FILTER_ENABLED = True
CRATE_OPENING_POINTS = np.array([
    [ 0.302, -0.77, 0.9],  # P1
    [-0.420, -0.77, 0.9],  # P2
    [-0.430, -0.33, 0.9],  # P3
    [ 0.300, -0.33, 0.9],  # P4
], dtype=np.float64)




 # np.array([[x, y, z], ... four rows ...])
CRATE_ENTRY_HYSTERESIS = 0.01  # [m], depth required to declare confinement
CRATE_HUMAN_STOP_DISTANCE = 0.50  # [m], early stop distance while confined

# Event-reporting thresholds. These affect messages only, not control behavior.
CBF_WARNING_H_THRESHOLD = 0.10
CBF_SCALING_INTERVENTION_THRESHOLD = 0.98


# ============================================================
# GRIPPER
# ============================================================

# Dataset convention:
#
# 0 = open
# 1 = closed

GRIPPER_SPEED = 40
GRIPPER_FORCE = 150

GRIPPER_MIN_CHANGE = 2


# ============================================================
# CAMERA
# ============================================================

def start_camera(serial):

    pipe = rs.pipeline()
    config = rs.config()

    config.enable_device(serial)

    config.enable_stream(
        rs.stream.color,
        CAM_W,
        CAM_H,
        rs.format.bgr8,
        CAM_FPS,
    )

    pipe.start(config)

    # Warm up camera
    for _ in range(10):
        pipe.wait_for_frames()

    return pipe


def get_image(pipe):

    frames = pipe.wait_for_frames()

    color = frames.get_color_frame()

    if not color:
        raise RuntimeError(
            "No camera frame received"
        )

    bgr = np.asanyarray(
        color.get_data()
    )

    rgb = cv2.cvtColor(
        bgr,
        cv2.COLOR_BGR2RGB,
    )

    rgb = image_tools.resize_with_pad(
        rgb,
        IMG_SIZE,
        IMG_SIZE,
    )

    return image_tools.convert_to_uint8(
        rgb
    )


# ============================================================
# GRIPPER
# ============================================================

def norm_to_gripper_raw(value):

    value = float(
        np.clip(
            value,
            0.0,
            1.0,
        )
    )

    return int(
        round(
            value * 255.0
        )
    )


def command_gripper(
    gripper,
    normalized_target,
    previous_raw,
):

    raw_target = norm_to_gripper_raw(
        normalized_target
    )

    if (
        previous_raw is None
        or abs(
            raw_target - previous_raw
        ) >= GRIPPER_MIN_CHANGE
    ):

        gripper.move(
            raw_target,
            GRIPPER_SPEED,
            GRIPPER_FORCE,
        )

        print(
            f" | gripper={normalized_target:.3f}"
            f" raw={raw_target}",
            end="",
        )

        return raw_target

    return previous_raw


# ============================================================
# CRATE GEOMETRY + CONFINED-SPACE CBF SUPERVISOR
# ============================================================

class CrateSafetyFilter:
    """Detect when the TCP is below the bounded crate-opening plane."""

    def __init__(
        self,
        model,
        monitored_frame_ids,
        opening_points,
        entry_hysteresis,
        human_stop_distance,
    ):
        points = np.asarray(opening_points, dtype=np.float64)
        if points.shape != (4, 3) or not np.all(np.isfinite(points)):
            raise ValueError("CRATE_OPENING_POINTS must contain four finite XYZ points")

        self.model = model
        self.data = model.createData()
        self.monitored_frame_ids = [int(frame_id) for frame_id in monitored_frame_ids]
        self.p0 = points[0].copy()

        edge_u = points[1] - points[0]
        edge_v = points[3] - points[0]
        width = float(np.linalg.norm(edge_u))
        if width <= 1e-6 or float(np.linalg.norm(edge_v)) <= 1e-6:
            raise ValueError("Crate opening edges must have non-zero length")

        self.axis_u = edge_u / width
        edge_v_orthogonal = edge_v - np.dot(edge_v, self.axis_u) * self.axis_u
        height = float(np.linalg.norm(edge_v_orthogonal))
        if height <= 1e-6:
            raise ValueError("Crate opening points do not define a plane")
        self.axis_v = edge_v_orthogonal / height
        self.normal = np.cross(self.axis_u, self.axis_v)
        self.normal /= np.linalg.norm(self.normal)

        planarity_error = np.max(np.abs((points - self.p0) @ self.normal))
        if planarity_error > 0.01:
            raise ValueError(
                f"Crate opening points are not planar (max error {planarity_error:.4f} m)"
            )

        opposite_u = float(np.dot(points[2] - self.p0, self.axis_u))
        opposite_v = float(np.dot(points[2] - self.p0, self.axis_v))
        self.width = 0.5 * (width + opposite_u)
        self.height = 0.5 * (height + opposite_v)

        self.entry_hysteresis = float(entry_hysteresis)
        self.human_stop_distance = float(human_stop_distance)

    def monitored_positions(self, q):
        q = np.asarray(q, dtype=np.float64)
        pin.framesForwardKinematics(self.model, self.data, q)
        return np.vstack([
            self.data.oMf[frame_id].translation.copy()
            for frame_id in self.monitored_frame_ids
        ])

    def coordinates(self, position):
        relative = np.asarray(position, dtype=np.float64) - self.p0
        u = float(np.dot(relative, self.axis_u))
        v = float(np.dot(relative, self.axis_v))
        signed_height = float(np.dot(relative, self.normal))
        return u, v, signed_height

    def inside_opening(self, position):
        u, v, _ = self.coordinates(position)
        return (
            0.0 <= u <= self.width
            and 0.0 <= v <= self.height
        )

    def is_confined(self, position):
        _, _, signed_height = self.coordinates(position)
        depth = -signed_height
        return depth >= self.entry_hysteresis and self.inside_opening(position)

    def human_is_close(self, q, obstacle_positions):
        obstacles = np.asarray(obstacle_positions, dtype=np.float64)
        if obstacles.size == 0:
            return False, float("inf")
        obstacles = obstacles.reshape(-1, 3)
        robot_points = self.monitored_positions(q)
        differences = robot_points[:, None, :] - obstacles[None, :, :]
        distances = np.linalg.norm(differences, axis=2)
        minimum_distance = float(np.min(distances))
        return minimum_distance <= self.human_stop_distance, minimum_distance

# ============================================================
# OBSERVATION + INFERENCE
# ============================================================

def capture_and_infer(
    policy,
    rtde_r,
    gripper,
    front_cam,
    wrist_cam,
):

    # --------------------------------------------------------
    # Robot state
    # --------------------------------------------------------

    q_now = np.asarray(
        rtde_r.getActualQ(),
        dtype=np.float32,
    )

    gripper_raw = (
        gripper.get_current_position()
    )

    gripper_norm = (
        float(gripper_raw)
        / 255.0
    )

    state = np.concatenate(
        [
            q_now,
            [gripper_norm],
        ]
    ).astype(np.float32)


    # --------------------------------------------------------
    # Images
    # --------------------------------------------------------

    front_rgb = get_image(
        front_cam
    )

    wrist_rgb = get_image(
        wrist_cam
    )


    # --------------------------------------------------------
    # Policy input
    # --------------------------------------------------------

    observation = {
        "state": state,
        "base_rgb": front_rgb,
        "wrist_rgb": wrist_rgb,
        "prompt": PROMPT,
    }


    # --------------------------------------------------------
    # π0.5
    # --------------------------------------------------------

    result = policy.infer(
        observation
    )

    actions = np.asarray(
        result["actions"],
        dtype=np.float64,
    )

    return actions, q_now


# ============================================================
# PREPARE / CLAMP POLICY TRAJECTORY
# ============================================================

def prepare_policy_chunk(
    actions,
    q_now,
):

    q_now = np.asarray(
        q_now,
        dtype=np.float64,
    )


    # ========================================================
    # Hard validity checks
    #
    # Invalid policy output should still terminate because
    # continuing from corrupt data is not useful.
    # ========================================================

    if actions.shape != (
        ACTION_HORIZON,
        7,
    ):

        raise RuntimeError(
            f"Expected "
            f"({ACTION_HORIZON}, 7), "
            f"got {actions.shape}"
        )


    if not np.all(
        np.isfinite(actions)
    ):

        raise RuntimeError(
            "Policy returned NaN or Inf"
        )


    # ========================================================
    # Select chunk
    # ========================================================

    raw_chunk = actions[
        :EXECUTE_ACTIONS
    ].copy()

    raw_joints = (
        raw_chunk[:, :6]
    )

    gripper_actions = np.clip(
        raw_chunk[:, 6],
        0.0,
        1.0,
    )


    # ========================================================
    # Diagnostics BEFORE clamping
    # ========================================================

    raw_first_delta = float(
        np.max(
            np.abs(
                raw_joints[0]
                - q_now
            )
        )
    )


    if EXECUTE_ACTIONS > 1:

        raw_step_delta = float(
            np.max(
                np.abs(
                    np.diff(
                        raw_joints,
                        axis=0,
                    )
                )
            )
        )

    else:

        raw_step_delta = 0.0


    raw_chunk_delta = float(
        np.max(
            np.abs(
                raw_joints
                - q_now
            )
        )
    )


    full_horizon_delta = float(
        np.max(
            np.abs(
                actions[:, :6]
                - q_now
            )
        )
    )


    # ========================================================
    # SAFE TRAJECTORY
    # ========================================================

    safe_joints = np.zeros_like(
        raw_joints
    )


    # --------------------------------------------------------
    # ACTION 0
    #
    # Limit first policy target relative to current actual
    # robot position.
    # --------------------------------------------------------

    safe_joints[0] = np.clip(
        raw_joints[0],
        q_now - MAX_FIRST_DELTA,
        q_now + MAX_FIRST_DELTA,
    )


    # --------------------------------------------------------
    # ACTIONS 1 ... N
    # --------------------------------------------------------

    for i in range(
        1,
        EXECUTE_ACTIONS,
    ):

        # Limit total displacement from observed position
        absolute_limited = np.clip(
            raw_joints[i],
            q_now - MAX_CHUNK_DELTA,
            q_now + MAX_CHUNK_DELTA,
        )


        # Limit action-to-action jump
        safe_joints[i] = np.clip(
            absolute_limited,
            safe_joints[i - 1]
            - MAX_STEP_DELTA,
            safe_joints[i - 1]
            + MAX_STEP_DELTA,
        )


        # Guarantee total chunk boundary
        safe_joints[i] = np.clip(
            safe_joints[i],
            q_now - MAX_CHUNK_DELTA,
            q_now + MAX_CHUNK_DELTA,
        )


    # ========================================================
    # Diagnostics AFTER clamping
    # ========================================================

    safe_first_delta = float(
        np.max(
            np.abs(
                safe_joints[0]
                - q_now
            )
        )
    )


    if EXECUTE_ACTIONS > 1:

        safe_step_delta = float(
            np.max(
                np.abs(
                    np.diff(
                        safe_joints,
                        axis=0,
                    )
                )
            )
        )

    else:

        safe_step_delta = 0.0


    safe_chunk_delta = float(
        np.max(
            np.abs(
                safe_joints
                - q_now
            )
        )
    )


    changed = np.any(
        np.abs(
            safe_joints
            - raw_joints
        ) > 1e-8,
        axis=1,
    )

    number_clamped = int(
        np.sum(changed)
    )


    # ========================================================
    # Print
    # ========================================================

    print(
        f"Raw first delta      : "
        f"{raw_first_delta:.5f} rad"
    )

    print(
        f"Raw step delta       : "
        f"{raw_step_delta:.5f} rad"
    )

    print(
        f"Raw {EXECUTE_ACTIONS} delta"
        f"      : "
        f"{raw_chunk_delta:.5f} rad"
    )

    print(
        f"Full horizon delta   : "
        f"{full_horizon_delta:.5f} rad"
    )


    if number_clamped:

        print(
            f"CLAMPED              : "
            f"{number_clamped}/"
            f"{EXECUTE_ACTIONS} actions"
        )

        print(
            f"Safe first delta     : "
            f"{safe_first_delta:.5f} rad"
        )

        print(
            f"Safe step delta      : "
            f"{safe_step_delta:.5f} rad"
        )

        print(
            f"Safe chunk delta     : "
            f"{safe_chunk_delta:.5f} rad"
        )

    else:

        print(
            "CLAMPED              : none"
        )


    print(
        f"Gripper next "
        f"{EXECUTE_ACTIONS}"
        f"      : "
        f"{np.min(gripper_actions):.3f}"
        f" -> "
        f"{np.max(gripper_actions):.3f}"
    )


    return (
        safe_joints,
        gripper_actions,
    )


# ============================================================
# PIECEWISE-LINEAR POLICY TRAJECTORY
# ============================================================

def build_linear_chunk_trajectory(
    q_start: np.ndarray,
    dq_start: np.ndarray,
    joint_actions: np.ndarray,
    dt_action: float = ACTION_DT,
    first_target_time: float = FIRST_TARGET_TIME,
):
    """
    Builds a piecewise-linear trajectory connecting the measured robot state at
    t=0 with the policy action targets. This matches the interpolation strategy
    used by maininferenceCode.py and cannot overshoot between target positions.

    Knots:
      t_0 = 0.0: q_start (with velocity dq_start)
      t_0 = first_target_time: joint_actions[0]
      t_k = first_target_time + k * dt_action: joint_actions[k], k in 1..N-1
      Total duration: first_target_time + (N - 1) * dt_action.

    Position is continuous. Nominal velocity is constant within each segment and
    nominal acceleration is zero; the CBF-QP enforces physical acceleration limits.
    """
    q_start = np.asarray(q_start, dtype=np.float64).reshape(6)
    np.asarray(dq_start, dtype=np.float64).reshape(6)  # Validate expected shape.
    joint_actions = np.asarray(joint_actions, dtype=np.float64)

    n_actions = len(joint_actions)
    if n_actions == 0:
        raise ValueError("joint_actions must contain at least one target")
    if first_target_time <= 0.0 or dt_action <= 0.0:
        raise ValueError("first_target_time and dt_action must be positive")

    action_times = first_target_time + np.arange(n_actions) * dt_action
    knot_times = np.concatenate(([0.0], action_times))
    chunk_duration = float(knot_times[-1])
    knot_positions = np.vstack([q_start, joint_actions])

    segment_durations = np.diff(knot_times)
    segment_velocities = np.diff(knot_positions, axis=0) / segment_durations[:, None]

    def segment_index(t):
        index = int(np.searchsorted(knot_times, t, side="right") - 1)
        return int(np.clip(index, 0, n_actions - 1))

    def trajectory_position(t):
        t_eval = float(np.clip(t, 0.0, chunk_duration))
        index = segment_index(t_eval)
        alpha = (t_eval - knot_times[index]) / segment_durations[index]
        alpha = float(np.clip(alpha, 0.0, 1.0))
        return knot_positions[index] + alpha * (
            knot_positions[index + 1] - knot_positions[index]
        )

    def trajectory_velocity(t):
        t_eval = float(np.clip(t, 0.0, chunk_duration))
        return segment_velocities[segment_index(t_eval)].copy()

    def trajectory_acceleration(t):
        del t
        return np.zeros(6, dtype=np.float64)

    return (
        trajectory_position,
        trajectory_velocity,
        trajectory_acceleration,
        chunk_duration,
    )


def get_spline_reference(
    trajectory_position,
    trajectory_velocity,
    trajectory_acceleration,
    tau: float,
    chunk_duration: float,
):
    """
    Evaluates nominal position, velocity, and acceleration from the spline at nominal time tau.
    """
    t_eval = float(np.clip(tau, 0.0, chunk_duration))
    nominal_q = trajectory_position(t_eval)
    nominal_Dq = trajectory_velocity(t_eval)
    nominal_DDq = trajectory_acceleration(t_eval)
    return nominal_q, nominal_Dq, nominal_DDq


# ============================================================
# HIGH FREQUENCY INNER CONTROL LOOP (500 Hz)
# ============================================================

def execute_chunk_500hz(
    ctrl,
    crate_filter,
    bridge,
    rtde_c,
    rtde_r,
    gripper,
    spline,
    spline_vel,
    spline_acc,
    gripper_actions,
    chunk_duration: float,
    last_gripper_raw: int,
    max_wall_time_scale: float = 3.0,
):
    """
    Executes the 500 Hz B-CBF optimal control loop over the chunk spline.

    In nominal conditions, runs while nominal time tau (ctrl.trajectory_time) < chunk_duration (1.5s).

    Retriggering / replanning strategies:
    1. Nominal completion: tau >= chunk_duration (completed 1.5s chunk)
    2. Tracking error: max(|q_cmd - q_actual|) > REPLAN_TRACKING_ERROR (0.15 rad)
    3. Controller unfeasibility: out["unfeasible_cnt"] == "UNFEASIBLE"
    4. Obstacle stagnation: wall time > chunk_duration * max_wall_time_scale with scaling < 0.2
    """
    step_count = 0
    start_wall_time = time.perf_counter()
    replan_triggered = False
    replan_reason = "COMPLETED"

    max_tracking_err = 0.0
    worst_tracking_joint = 0
    h_min_overall = float("inf")
    d_min_overall = float("inf")
    scalings = []
    cbf_intervention_reported = False

    max_wall_time = chunk_duration * max_wall_time_scale

    try:
        while True:
            loop_start = time.perf_counter()
            wall_elapsed = loop_start - start_wall_time

            # ----------------------------------------------------
            # 1. Check Nominal Completion Condition
            # ----------------------------------------------------
            tau = ctrl.trajectory_time
            if tau >= chunk_duration:
                replan_triggered = False
                replan_reason = "COMPLETED"
                break

            # ----------------------------------------------------
            # 2. Check Obstacle Stagnation (Timeout) Retriggering
            # ----------------------------------------------------
            if wall_elapsed > max_wall_time and ctrl.Dtrajectory_time < 0.2:
                replan_triggered = True
                replan_reason = "OBSTACLE_STAGNATION"
                print(
                    f"\n[CBF Replan] Stagnation detected: wall time ({wall_elapsed:.2f}s) "
                    f"exceeded max allowed ({max_wall_time:.2f}s) with scale={ctrl.Dtrajectory_time:.3f}."
                )
                break

            # ----------------------------------------------------
            # 3. Synchronize RTDE control period (500 Hz = 0.002s)
            # ----------------------------------------------------
            period = None
            if rtde_c is not None:
                period = rtde_c.initPeriod()

            # ----------------------------------------------------
            # 4. Perception: Get Obstacles from Bridge
            # ----------------------------------------------------
            if bridge is not None:
                obs_pos, obs_vel, obs_acc = bridge.getObstacles()
            else:
                obs_pos = np.zeros((0, 3), dtype=np.float64)
                obs_vel = np.zeros((0, 3), dtype=np.float64)
                obs_acc = np.zeros((0, 3), dtype=np.float64)

            # ----------------------------------------------------
            # 5. Confined-space human stop (before the CBF step)
            # ----------------------------------------------------
            if crate_filter is not None:
                if rtde_r is not None:
                    tcp_position = np.asarray(
                        rtde_r.getActualTCPPose()[:3],
                        dtype=np.float64,
                    )
                else:
                    tcp_position = crate_filter.monitored_positions(ctrl.q)[0]

                confined = crate_filter.is_confined(tcp_position)
                if rtde_r is not None:
                    current_q = np.asarray(rtde_r.getActualQ(), dtype=np.float64)
                else:
                    current_q = ctrl.q.copy()
                human_close, human_distance = crate_filter.human_is_close(
                    current_q,
                    obs_pos,
                )
                if confined and human_close:
                    hold_q = current_q
                    if rtde_c is not None:
                        rtde_c.servoJ(
                            hold_q.tolist(),
                            0.0,
                            0.0,
                            SERVO_DT,
                            LOOKAHEAD_TIME,
                            GAIN,
                        )
                    replan_triggered = True
                    replan_reason = "CRATE_CONFINED_HUMAN"
                    print(
                        f"\n[Crate Filter] TCP confined and human distance "
                        f"{human_distance:.3f} m <= "
                        f"{crate_filter.human_stop_distance:.3f} m. Holding and replanning."
                    )
                    break

            # ----------------------------------------------------
            # 6. Query Spline Reference (C^2 continuous)
            # ----------------------------------------------------
            nominal_q, nominal_Dq, nominal_DDq = get_spline_reference(
                spline,
                spline_vel,
                spline_acc,
                tau,
                chunk_duration,
            )

            # ----------------------------------------------------
            # 7. Step B-CBF Optimal Controller
            # ----------------------------------------------------
            out = ctrl.step(
                obs_pos=obs_pos,
                obs_vel=obs_vel,
                obs_acc=obs_acc,
                nominal_q=nominal_q,
                nominal_Dq=nominal_Dq,
                nominal_DDq=nominal_DDq,
            )

            q_cmd = out["q"]
            dq_cmd = out["dq"]
            ddq_cmd = out["ddq"]
            new_tau = out["trajectory_time"]
            unfeasible_status = out["unfeasible_cnt"]
            scaling = out["Dtrajectory_time"]
            h_min = out["h_min"]
            d_min = out["d_min"]

            scalings.append(scaling)
            h_min_overall = min(h_min_overall, h_min)
            d_min_overall = min(d_min_overall, d_min)

            obstacle_count = int(obs_pos.shape[0])
            cbf_intervening = obstacle_count > 0 and (
                h_min <= CBF_WARNING_H_THRESHOLD
                or scaling <= CBF_SCALING_INTERVENTION_THRESHOLD
            )
            if cbf_intervening and not cbf_intervention_reported:
                print(
                    f"\n[CBF Triggered] h_min={h_min:.3f} m | "
                    f"d_min={d_min:.3f} m | scale={scaling:.3f}"
                )
                cbf_intervention_reported = True
            elif not cbf_intervening and cbf_intervention_reported:
                print(
                    f"\n[CBF Cleared] h_min={h_min:.3f} m | "
                    f"d_min={d_min:.3f} m | scale={scaling:.3f}"
                )
                cbf_intervention_reported = False

            # ----------------------------------------------------
            # 8. Actuation: Send Command to Robot
            # ----------------------------------------------------
            if rtde_c is not None:
                rtde_c.servoJ(
                    q_cmd.tolist(),
                    0.0,
                    0.0,
                    SERVO_DT,
                    LOOKAHEAD_TIME,
                    GAIN,
                )

            if bridge is not None:
                try:
                    bridge.sendCommand(q_cmd)
                except Exception:
                    pass

            # ----------------------------------------------------
            # 8. Gripper: Update based on chunk progress
            # ----------------------------------------------------
            if gripper is not None and len(gripper_actions) > 0:
                if tau < FIRST_TARGET_TIME:
                    action_idx = 0
                else:
                    action_idx = 1 + int(
                        (tau - FIRST_TARGET_TIME) / ACTION_DT
                    )
                action_idx = min(action_idx, len(gripper_actions) - 1)
                last_gripper_raw = command_gripper(
                    gripper,
                    gripper_actions[action_idx],
                    last_gripper_raw,
                )

            # ----------------------------------------------------
            # 9. Feedback & Tracking Error Diagnostics
            # ----------------------------------------------------
            if rtde_r is not None:
                q_actual = np.asarray(rtde_r.getActualQ(), dtype=np.float64)
            else:
                q_actual = q_cmd.copy()

            err_per_joint = np.abs(q_cmd - q_actual)
            tracking_error = float(np.max(err_per_joint))
            worst_joint = int(np.argmax(err_per_joint))

            if tracking_error > max_tracking_err:
                max_tracking_err = tracking_error
                worst_tracking_joint = worst_joint

            step_count += 1

            # Print status periodically (every 50 ms = 25 steps @ 500 Hz).
            # A 1e9 barrier value is an internal no-obstacle sentinel, so never
            # display it as a real measured distance.
            if step_count % 25 == 0:
                if obstacle_count:
                    proximity = f"d_min={d_min:.3f}m | h_min={h_min:.3f}m"
                else:
                    proximity = "d_min=N/A | h_min=N/A | PERCEPTION EMPTY"
                print(
                    f"\r[500Hz] tau={new_tau:5.2f}/{chunk_duration:.2f}s | "
                    f"CBF={'ON' if ctrl.useCbf else 'OFF'} | obs={obstacle_count} | "
                    f"scale={scaling:.3f} | {proximity} | "
                    f"err={tracking_error:.4f} rad (J{worst_joint + 1}) | "
                    f"{unfeasible_status}",
                    end="",
                    flush=True,
                )

            # ----------------------------------------------------
            # 10. Replan Retriggering Check: Tracking Error
            # ----------------------------------------------------
            if tracking_error > REPLAN_TRACKING_ERROR:
                replan_triggered = True
                replan_reason = "TRACKING_ERROR"
                print(
                    f"\n[CBF Replan] Tracking error ({tracking_error:.4f} rad, J{worst_joint + 1}) "
                    f"exceeded threshold ({REPLAN_TRACKING_ERROR:.4f} rad)."
                )
                break

            # ----------------------------------------------------
            # 11. Replan Retriggering Check: Unfeasible State
            # ----------------------------------------------------
            if unfeasible_status == "UNFEASIBLE":
                replan_triggered = True
                replan_reason = "UNFEASIBLE"
                print(
                    f"\n[CBF Replan] Controller triggered emergency deceleration (UNFEASIBLE QP)."
                )
                break

            # ----------------------------------------------------
            # 12. Period Sync (500 Hz)
            # ----------------------------------------------------
            if rtde_c is not None and period is not None:
                rtde_c.waitPeriod(period)
            else:
                elapsed_total = time.perf_counter() - loop_start
                rest = SERVO_DT - elapsed_total
                if rest > 0:
                    time.sleep(rest)

    except KeyboardInterrupt:
        replan_triggered = True
        replan_reason = "INTERRUPTED"
        raise

    finally:
        print()  # Newline after \r prints

    # Read final actual state
    if rtde_r is not None:
        q_final = np.asarray(rtde_r.getActualQ(), dtype=np.float64)
        try:
            dq_final = np.asarray(rtde_r.getActualQd(), dtype=np.float64)
        except Exception:
            dq_final = ctrl.dq.copy()
    else:
        q_final = ctrl.q.copy()
        dq_final = ctrl.dq.copy()

    stats = {
        "step_count": step_count,
        "max_tracking_err": max_tracking_err,
        "worst_joint": worst_tracking_joint,
        "h_min": h_min_overall,
        "d_min": d_min_overall,
        "mean_scaling": float(np.mean(scalings)) if scalings else 1.0,
        "wall_elapsed": time.perf_counter() - start_wall_time,
        "nominal_time": ctrl.trajectory_time,
    }

    return replan_triggered, replan_reason, q_final, dq_final, last_gripper_raw, stats


# ============================================================
# HOLD WHILE π0.5 IS RUNNING (500 Hz)
# ============================================================

def hold_while_inferencing(
    rtde_c,
    future,
    hold_target,
):
    hold_target = np.asarray(
        hold_target,
        dtype=np.float64,
    )

    while not future.done():
        if rtde_c is not None:
            period = rtde_c.initPeriod()
            rtde_c.servoJ(
                hold_target.tolist(),
                0.0,
                0.0,
                SERVO_DT,
                LOOKAHEAD_TIME,
                GAIN,
            )
            rtde_c.waitPeriod(period)
        else:
            time.sleep(SERVO_DT)


# ============================================================
# MAIN
# ============================================================

def main():

    rtde_r = None
    rtde_c = None
    bridge = None
    crate_filter = None

    gripper = None

    front_cam = None
    wrist_cam = None

    executor = None


    try:

        # ====================================================
        # CONNECTIONS
        # ====================================================

        print(
            "Connecting to UR10e..."
        )

        rtde_r = (
            rtde_receive.RTDEReceiveInterface(
                ROBOT_IP,
                frequency=SERVO_HZ,
            )
        )


        print(
            "Connecting to gripper..."
        )

        gripper = (
            RobotiqCModelURCap(
                ROBOT_IP
            )
        )


        print(
            "Starting front camera..."
        )

        front_cam = start_camera(
            FRONT_SERIAL
        )


        print(
            "Starting wrist camera..."
        )

        wrist_cam = start_camera(
            WRIST_SERIAL
        )


        print(
            "Connecting to policy server..."
        )

        policy = (
            websocket_client_policy
            .WebsocketClientPolicy(
                host=SERVER_HOST,
                port=SERVER_PORT,
            )
        )


        executor = ThreadPoolExecutor(
            max_workers=1
        )


        # ====================================================
        # INITIAL OBSERVATION + INFERENCE
        # ====================================================

        print(
            "\nRunning initial policy inference..."
        )


        actions, q_observed = (
            capture_and_infer(
                policy,
                rtde_r,
                gripper,
                front_cam,
                wrist_cam,
            )
        )


        joint_actions, gripper_actions = (
            prepare_policy_chunk(
                actions,
                q_observed,
            )
        )


        # ====================================================
        # INFO
        # ====================================================

        print(
            "\n" + "=" * 75
        )

        print(
            "π0.5 CLOSED-LOOP EXECUTION"
        )

        print(
            "=" * 75
        )

        print(
            f"Servo rate          : "
            f"{SERVO_HZ} Hz"
        )

        print(
            f"Action rate         : "
            f"{ACTION_HZ} Hz"
        )

        print(
            f"Servo steps/action  : "
            f"{SERVO_STEPS_PER_ACTION}"
        )

        print(
            f"Servo rate          : "
            f"{SERVO_HZ} Hz"
        )

        print(
            f"Action rate         : "
            f"{ACTION_HZ} Hz"
        )

        print(
            f"Policy horizon      : "
            f"{ACTION_HORIZON}"
        )

        print(
            f"Max actions/infer   : "
            f"{EXECUTE_ACTIONS}"
        )

        print(
            f"Nominal chunk time  : "
            f"{CHUNK_DURATION:.2f} s"
        )

        print(
            f"Replan error thresh : "
            f"{REPLAN_TRACKING_ERROR:.3f} rad"
        )

        print(
            "Trajectory profile  : Piecewise linear (no target overshoot)"
        )

        print(
            "Inner controller    : B-CBF Optimal Controller @ 500 Hz"
        )

        print(
            "Tracking error action: REPLAN, NOT STOP"
        )


        input(
            "\nKeep emergency stop ready.\n"
            "Press ENTER to begin..."
        )


        # ====================================================
        # RTDE CONTROL
        # ====================================================

        print(
            "\nConnecting RTDE control..."
        )

        rtde_c = (
            rtde_control.RTDEControlInterface(
                ROBOT_IP,
                SERVO_HZ,
            )
        )


        last_gripper_raw = (
            gripper.get_current_position()
        )

        # ====================================================
        # CBF CONTROLLER INITIALIZATION
        # ====================================================

        config = load_config()
        robot_cfg = config.get("robot", {})
        joint_names = robot_cfg.get("joint_names", [
                "ur10e_shoulder_pan_joint",
                "ur10e_shoulder_lift_joint",
                "ur10e_elbow_joint",
                "ur10e_wrist_1_joint",
                "ur10e_wrist_2_joint",
                "ur10e_wrist_3_joint",
            ])

        # 1. Load Robot Kinematic & Dynamic Model
        model_wrapper = loadSharework(joint_names)
        model = model_wrapper.model

        # 2. Configure Controller
        cfg, ctrl = setup_controller(model_wrapper, config)
        cfg.Tc = SERVO_DT

        # Apply the conservative planner scales to the real-time CBF-QP limits.
        # setup_controller() otherwise leaves the controller at its full default
        # limits (pi rad/s and 12.7 rad/s^2), which can create aggressive
        # avoidance motion near a human.
        planner_cfg = config.get("planner", {})
        cbf_velocity_scale = float(planner_cfg.get("dq_max_scale", 0.25))
        cbf_acceleration_scale = float(planner_cfg.get("ddq_max_scale", 0.125))
        if not 0.0 < cbf_velocity_scale <= 1.0:
            raise ValueError("planner.dq_max_scale must be in (0, 1]")
        if not 0.0 < cbf_acceleration_scale <= 1.0:
            raise ValueError("planner.ddq_max_scale must be in (0, 1]")
        cfg.Dq_max *= cbf_velocity_scale
        cfg.DDq_max *= cbf_acceleration_scale

        print(cfg)
        print(
            "CBF motion limits   : "
            f"velocity scale={cbf_velocity_scale:.3f}, "
            f"acceleration scale={cbf_acceleration_scale:.3f}"
        )

        if CRATE_FILTER_ENABLED:
            if CRATE_OPENING_POINTS is None:
                raise ValueError(
                    "CRATE_FILTER_ENABLED is True but CRATE_OPENING_POINTS is not configured"
                )
            crate_filter = CrateSafetyFilter(
                model=model,
                monitored_frame_ids=ctrl.frames_ids,
                opening_points=CRATE_OPENING_POINTS,
                entry_hysteresis=CRATE_ENTRY_HYSTERESIS,
                human_stop_distance=CRATE_HUMAN_STOP_DISTANCE,
            )
            print(
                "Crate safety filter: ENABLED | "
                f"opening={crate_filter.width:.3f} x {crate_filter.height:.3f} m | "
                "no depth restriction"
            )
        else:
            print("Crate safety filter: DISABLED")

        bridge_cfg = config.get("bridge", {})
        threshold = float(bridge_cfg.get("threshold", 1.1))
        timeout_sec = float(bridge_cfg.get("timeout_sec", 5.0))
        obstacles_topics = list(bridge_cfg.get("obstacles_topics", []))
        kinematics_topics = list(bridge_cfg.get(
            "kinematics_topics",
            ["/zed/zed_node/body_trk/skeletons_kinematics"],
        ))
        bridge = JointStateCommandBridge(
            ordered_joint_names=joint_names,
            threshold=threshold,
            obstacles_topics=obstacles_topics,
            kinematics_topics=kinematics_topics,
        )
        tool_frame_name = cfg.tool_frame

        first_joint_position = bridge.wait_for_first_state(tool_frame_name, timeout=timeout_sec)
        if math.isnan(first_joint_position):
            bridge.shutdown()
            return
        first_joint_position = bridge.getPositions()

        # Stop servo motion and bridge immediately on Ctrl+C, then run normal cleanup.
        signal.signal(
            signal.SIGINT,
            functools.partial(_handle_robot_sigint, rtde_c, bridge),
        )

        # ====================================================
        # CONTINUOUS CLOSED LOOP
        # ====================================================

        cycle = 1

        # Initialize current robot joint states
        q_actual = np.asarray(
            rtde_r.getActualQ(),
            dtype=np.float64,
        )
        try:
            dq_actual = np.asarray(
                rtde_r.getActualQd(),
                dtype=np.float64,
            )
        except Exception:
            dq_actual = np.zeros(6, dtype=np.float64)

        while True:

            print(
                "\n" + "=" * 75
            )

            print(
                f"CYCLE {cycle}"
            )

            print(
                "=" * 75
            )

            # ------------------------------------------------
            # 1. Build the piecewise-linear trajectory for this chunk
            # ------------------------------------------------
            spline, spline_vel, spline_acc, chunk_duration = build_linear_chunk_trajectory(
                q_start=q_actual,
                dq_start=dq_actual,
                joint_actions=joint_actions,
                dt_action=ACTION_DT,
            )

            # ------------------------------------------------
            # 2. Reset CBF controller state for this chunk
            # ------------------------------------------------
            ctrl.reset_state(q_actual, dq_actual)

            # ------------------------------------------------
            # 3. Execute 500 Hz High-Frequency Control Loop
            # ------------------------------------------------
            (
                early_replan,
                replan_reason,
                q_actual,
                dq_actual,
                last_gripper_raw,
                stats,
            ) = execute_chunk_500hz(
                ctrl=ctrl,
                crate_filter=crate_filter,
                bridge=bridge,
                rtde_c=rtde_c,
                rtde_r=rtde_r,
                gripper=gripper,
                spline=spline,
                spline_vel=spline_vel,
                spline_acc=spline_acc,
                gripper_actions=gripper_actions,
                chunk_duration=chunk_duration,
                last_gripper_raw=last_gripper_raw,
            )

            # ------------------------------------------------
            # 4. Position to hold during next inference
            # ------------------------------------------------
            hold_target = q_actual.copy()

            # ------------------------------------------------
            # 5. Observe Scene and Run Next Inference Asynchronously
            # ------------------------------------------------
            print(
                "Observing scene and running next inference..."
            )

            future = executor.submit(
                capture_and_infer,
                policy,
                rtde_r,
                gripper,
                front_cam,
                wrist_cam,
            )

            # Keep servoJ alive at 500 Hz holding current position
            hold_while_inferencing(
                rtde_c,
                future,
                hold_target,
            )

            # Receive fresh prediction
            actions, q_observed = future.result()

            joint_actions, gripper_actions = prepare_policy_chunk(
                actions,
                q_observed,
            )

            print(
                f"Cycle {cycle} finished | Reason: {replan_reason} | "
                f"Steps: {stats['step_count']} | Wall time: {stats['wall_elapsed']:.2f}s | "
                f"Nominal time: {stats['nominal_time']:.2f}/{chunk_duration:.2f}s | "
                f"Mean scaling: {stats['mean_scaling']:.3f} | "
                f"Max error: {stats['max_tracking_err']:.4f} rad"
            )

            cycle += 1


    # ========================================================
    # USER STOP
    # ========================================================

    except KeyboardInterrupt:

        print(
            "\n\nExecution stopped by user."
        )


    # ========================================================
    # ACTUAL HARD ERROR
    #
    # Examples:
    # camera failure
    # RTDE failure
    # server failure
    # NaN policy output
    # ========================================================

    except Exception as exc:

        print(
            f"\nHARD ERROR: {exc}"
        )


    # ========================================================
    # CLEANUP
    # ========================================================

    finally:

        print(
            "\nStopping robot..."
        )


        if rtde_c is not None:

            try:
                rtde_c.servoStop()
            except Exception:
                pass

            try:
                rtde_c.stopScript()
            except Exception:
                pass


        if bridge is not None:

            try:
                bridge.shutdown()
            except Exception:
                pass


        if executor is not None:

            try:
                executor.shutdown(
                    wait=False,
                    cancel_futures=True,
                )
            except Exception:
                pass


        if front_cam is not None:

            try:
                front_cam.stop()
            except Exception:
                pass


        if wrist_cam is not None:

            try:
                wrist_cam.stop()
            except Exception:
                pass


        if rtde_r is not None:

            try:
                rtde_r.disconnect()
            except Exception:
                pass


        if gripper is not None:

            try:
                gripper.disconnect()
            except Exception:
                pass


        print(
            "Done."
        )


if __name__ == "__main__":
    main()
